# Generated by Django 3.2.6 on 2021-09-01 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='shared_url',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
